name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:  # 一个job由一个或多个step组成
      - name: Check out the repo
        uses: actions/checkout@v3   # 官方的action，获取代码
      - name: Build Image
        run: |
          docker build -t mrzhang3389/fastppocr .

      - name: Login to Registry
        run: docker login --username=${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Image
        run: |
          docker push mrzhang3389/fastppocr
