name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: user/app:latest
          

  # build:

  #   runs-on: ubuntu-latest

  #   steps:  # 一个job由一个或多个step组成
  #     - name: Check out the repo
  #       uses: actions/checkout@v3   # 官方的action，获取代码

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     # GitHub Repo => Settings => Secrets 增加 docker hub 登录密钥信息
      #     # DOCKERHUB_USERNAME 是 docker hub 账号名.
      #     # DOCKERHUB_TOKEN: docker hub => Account Setting => Security 创建.
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build Image
      #   run: |
      #     docker build -t mrzhang3389/fastppocr:latest .
        
      # - name: Push Image
      #   run: |
      #     docker push mrzhang3389/fastppocr:latest

      # - name: Build and Push to DockerHub
      #     # You may pin to the exact commit or the version.
      #     # uses: MaximilianoBz/dockerhub-buildpush@372110d600041736063b948d05005b6039d8fb0c
      #   uses: MaximilianoBz/dockerhub-buildpush@v1.1
      #   with:
      #     # Docker Registry Url, eg: docker.io
      #     registry_url: docker.io
      #     # Docker Image Repository Name, eg: username/demo-app
      #     repository_name: mrzhang3389/fastppocr
      #     # Docker Login UserName, from: https://hub.docker.com/
      #     user_name: ${{ secrets.DOCKERHUB_USERNAME }}
      #     # Docker Login Access Token, from: https://hub.docker.com/
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #     # Image Build Version
      #     image_version: latest
      #     # Docker File Directory, Default Current Directory (.)
      #     docker_file: . # optional, default is .
