name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:  # 一个job由一个或多个step组成
      - name: Check out the repo
        uses: actions/checkout@v3   # 官方的action，获取代码

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # GitHub Repo => Settings => Secrets 增加 docker hub 登录密钥信息
          # DOCKERHUB_USERNAME 是 docker hub 账号名.
          # DOCKERHUB_TOKEN: docker hub => Account Setting => Security 创建.
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        run: |
          docker build -t mrzhang3389/fastppocr:latest .
        
      - name: Push Image
        run: |
          docker push mrzhang3389/fastppocr:latest
          
